### ISSUE TITLE
Server Side Search Deletes Search Text

### ISSUE THREAD

**Issue by mhmcdonald** [grid-js/gridjs#1081]
**Describe the bug**
I've noticed that when I use server side search and type in search text at a reasonable pace, some of the most recent text will get deleted. This behavior can be seen in [this gif](https://giphy.com/gifs/Z24Jt2XAMqz3j8P3WB). This results in mistakes while entering your search phrase because the text you're typing in gets changed so easily/unexpectedly.  

I've noticed this bug on my own projects as well as on the server-side search example on the grid.js documentation site. 

**To Reproduce**
1. Go to the server side search example on grid.js website: https://gridjs.io/docs/examples/server-side-search/
2. Scroll down to the search box
3. Type in the word 'empire' at a normal typing pace (if you type very slow or very fast you may not be able to reproduce this issue).
4. Notice how the last letter (or couple of letters) that you've typed in gets deleted from the search box. Similarly, if you've made a mistake and you click delete on your key board, your delete may not take effect. This results in incorrect search terms being entered into the search box. 

**Expected behavior**
The server-side search feature returns filtered table records as soon as you start typing. The text that I type into the search box should not be altered/edited. 

**Screenshots**
You can see this bug in [this gif](https://giphy.com/gifs/Z24Jt2XAMqz3j8P3WB). 

In this gif, I'm typing in the word 'empire' into the search bar. After typing in the first three letters, 'emp' the table returns results for 'em'. However the in the search box, the 'p' has been deleted from my search text (you can see the 'emp' for a split second before the 'p' gets removed). It accepts my fourth letter typed in ('i') so then I have the incorrect search text of 'emi'. Towards the end of the gif you can see I have the same buggy experience trying to type in the letter 'r' (it gets deleted from the search text box very quickly after I've typed it in). 

**Desktop (please complete the following information):**
 - OS: Monterey 
 - Browser: chrome
 - Version: 103.0.5060

**Comment by Aloysb** [comment]
@mhmcdonald Same issue here.

There's is a 'racing' condition when typing.

Typing triggers a server call.
Depending on how fast/slow it responds, you will experience the issue.

This does not occur when typing fast since the debouncing takes care of it. 
If typing 'slow', then the server has the time to respond.

Not that if you have a slow connection, it would make the matter even worse - as in you will have to type fast, or very slow.

But if you hit the 'wrong' speed when typing, it gets out of hand :smiley: 

Notice on the video the server calls on the right. When they return, they override the input value.

https://user-images.githubusercontent.com/17796338/184734929-1a32e539-145a-41ae-a89e-2bbad39a27a8.mp4


I believe the way to work around that would be to decouple the searching from the rendering.

I'm happy to open a PR for that, I found the issue, just give me a day or two :+1:

**Comment by Aloysb** [comment]
Made a bit of progress here - not as much as expected.
The library is heavily relying on inheritance and events, it took me a while to find my way around 😄 

So, it turns out it is an issue related to the way we debounce the user input - there might be no racing conditions with the server as I initially thought.

I'll try to keep you updated soon once I've done more digging 🔧 👍

**Comment by mhmcdonald** [comment]
Thanks for the update @Aloysb - I really appreciate you digging into this

**Comment by Aloysb** [comment]
There you go! 🍻 

It seems that sometimes the answer is just *KISS* Keep it simple, stupid.

There is no need to have the search input controlled (at least, at this stage) - and it would create a racing condition.

Rather than having the current input and the current search stored separately, I've simply turned the input into a plain ol' uncontrolled component and ... tada! 🎉  no more racing condition 👍

**Comment by mhmcdonald** [comment]
Amazing, thank you @Aloysb! You rock! I will be watching the PR.

**Comment by Aloysb** [comment]
Hey @mhmcdonald ,

Just to let you know that we'll aim to get this reviewed soon, maybe next week 👍

**Comment by mhmcdonald** [comment]
thanks again for the update @Aloysb!

**Comment by nitinmalik1997** [comment]
> There you go! 🍻 @mhmcdonald
> 
> Feel free to pull on that branch until the PR is merged.
> 
> It seems that sometimes the answer is just _KISS_ Keep it simple, stupid. Look at how small the code changes I've made are 😄
> 
> There is no need to have the search input controlled (at least, at this stage) - and it does create a racing condition.
> 
> Rather than having the current input and the current search stored separately, I've simply turned the input into a plain ol' uncontrolled component since it doesn't HAVE to be controlled and ... tada! 🎉 no more racing condition 👍

Could you please elaborate how to turn the input into a plain of uncontrolled component?

**Comment by abitbetterthanyesterday** [comment]
Sure,
Just check out the open PR, it's literally removing one line of code.

Basically, you want to let the input control its own state rather than
managing it from the outside (by *not* setting `value={ ... }`).

The search is watching the onChange event, so there is no real need to
control the input value.

There is a race condition on the onChange, due to the fact that there is a
debounce on the call.

"onChange -> debounce -> call server -> return and update the value".

However, if the user had typed more characters during the trip to the
server, then it is overriden when the server respond. That's where the bug
is coming from.

It only happens if you type in sync with the debounce period.

If you type slowly, each event is sent to the server and returned in time.

If you type fast, then you never trigger the debounce - only when you stop
typing.

But if you type at the *wrong* speed, you create this racing condition.

**Comment by newmediacrew** [comment]
I have the same problem. Gonna look into this

**Comment by hrvoje-grabusic** [comment]
> But if you type at the *wrong* speed, you create this racing condition.
Increasing the wrong speed is quick fix from the config side meanwhile. 
debounceTimeout:1000,
Works for me.

**Comment by newmediacrew** [comment]
> > But if you type at the _wrong_ speed, you create this racing condition.
> 
> Increasing the wrong speed is quick fix from the config side meanwhile. debounceTimeout:1000, Works for me.

Where did you set the value of debounceTimeout:1000 ?

**Comment by hrvoje-grabusic** [comment]
> Where did you set the value of debounceTimeout:1000 ?

In the search block
` search: {
            debounceTimeout:1000,
            server: {
                url: (prev, keyword) => `${prev}&search=${keyword}`
            }
        },`

It's in the docs:
[](https://gridjs.io/docs/config/search)

**Comment by newmediacrew** [comment]
> > Where did you set the value of debounceTimeout:1000 ?
> 
> In the search block `search: { debounceTimeout:1000, server: { url: (prev, keyword) =>`prev?search={keyword}` } },`
> 
> It's in the docs: [gridjs.io/docs/config/search](https://gridjs.io/docs/config/search)

Just a matter for RTFM, thank you for that.

**Comment by afshinm** [comment]
https://github.com/grid-js/gridjs/pull/1267 can potentially fix this issue. Can someone run some tests on that branch please?

**Comment by mnsrulz** [comment]
> #1267 can potentially fix this issue. Can someone run some tests on that branch please?
The issue still persists.

**Comment by adamhwang** [comment]
This happens for client side as well with a reasonable amount of data (~800 total rows, 100 rows/page, 10+ cols)
