### ISSUE TITLE
customize search box. We can use another input for search?

### ISSUE THREAD

**Issue by puuble** [grid-js/gridjs#1258]
I want to customize the search box.
The place where the search box is created doesn't look nice in my theme. I made a new place for the search box in my theme and I want to search from that input. Is this possible?

**Comment by MehdiBenbahri** [comment]
If i where you, i will firstly make a custom plugin : 
https://gridjs.io/docs/plugins/basics/#introduction 
(i call him custom search box for example)
With this when you will place your search box you can choose exactly where : 

```
grid.plugin.add({
  id: 'myfirstplugin',
  component: MyPlugin,
  position: PluginPosition.Header,
  order: 1,
});
```
For the searching himself, we have to know what you are using for the request, if you got searching parameters in the endpoint (limit, order, search param, keyword) ?

It will depend of the purpose / behavior of the search boxtoo. You have to treat the search in the back end most of the time due to performance.

Bref, you have to engineer before coding

**Comment by afshinm** [comment]
+1 to what @MehdiBenbahri suggested.
