### ISSUE TITLE
Request to mark this Library Unmaintained if it is not being updated anymore

### ISSUE THREAD

**Issue by dev-gush** [grid-js/gridjs#1394]
i see this repo was last updated January this year. Also, a lot of issues are unresolved and unanswered by the Authors.

I built a lot of features around this library just to discover a lot of bugs.

**Comment by fabanc** [comment]
+ 1. I would love to help but bug fixes or enhancement through pull requests are no going through. I would like to support that library but pull requests aren't getting in, no matter how small. Help us help you. There is a lot of love for the work that has been done there, and I would like to see the project grow and help. But first, it would be nice to know if this project is still active. Otherwise I might need to look for another solution.

**Comment by dev-gush** [comment]
Seems like its not active anymore. We switched to Tanstack Tables.

**Comment by afshinm** [comment]
Sorry folks, it's been difficult for me to keep track of all the issues but I will look into major issues asap. Thanks for being patient.
