### ISSUE TITLE
Improve German translations

### ISSUE THREAD

**Issue by GitRon** [grid-js/gridjs#1416]
**Describe the bug**
The German translation is a little clunky and wrong at some points.

**To Reproduce**
Turn on German translation as a native speaker.

**Expected behavior**
Proper German 🙃 

I'll provide a PR in a second.

Best regards  
Ronny

**Comment by rubycon** [comment]
I agree, the issue comes from how translation is handled and not the translations themselves : 
- https://github.com/grid-js/gridjs/blob/master/l10n/de_DE.ts

The translation is done on an word basis (`showing`, `of`, `to`, `results`...) instead of sentences, which is usually how its done in most project.

**Comment by GitRon** [comment]
Hi @rubycon! Thx! Nevertheless, I'd be happy to get the translation update in ASAP since I want to use it in a German webapp 🙂 The other thing should be handled in a separate ticket - since we'd have to update all other translation files as well.

**Comment by GitRon** [comment]
@daniel-werner I saw you in the contributor list and I guess you are German-speaking by your name? Could you give an estimate when my small PR might be reviewed?

Thx and sorry for being pushy!  
Ronny

**Comment by christoph-teichmeister** [comment]
Just bumped into this myself. +1 on this!

**Comment by GitRon** [comment]
Awesome, thx @afshinm!
