### ISSUE TITLE
Set a custom ID

### ISSUE THREAD

**Issue by cedriking** [grid-js/gridjs#164]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
Add the option to set custom IDs to cells, this way with the `onClick` event, be able to grab the right ID and interact with it.

Example, I have a row with a username, when I click on it what I want is the ID of the user and then being able to do requests to my server with that user ID.

**Describe alternatives you've considered**
I'm using formatter with an Array that includes the username + ID, still sounds like a better option if we are able to set the ID to the row. 

What I have so far:
```
formatter: (cell) => html(`<span data-id="${cell[1]}">${cell[0]}</span>`)
```

**Comment by afshinm** [comment]
@cedriking each Grid.js row has a unique UUID: https://codesandbox.io/s/gridjs-hello-world-yrgp2?file=/src/index.js

Do you think you can use that UUID to achieve what you're after?

**Comment by cedriking** [comment]
Thanks @afshinm for the quick reply. Yes, that's the one I was hoping I could change to the userID. Right now it's something done by default, can we set that ID to something else?

**Comment by afshinm** [comment]
@cedriking no, it's not possible right now but I'm happy to change it.

**Comment by mdennisa** [comment]
I think this would be a great feature.
The limitation with formatter currently is that we can only access the data that is specified by columns.

In more specific case, we want to access specific data reference from the data object instead of columns, and there are some cases where specific data is not displayed to preserve the column size.

example: 
```
...
columns: [
  { id: "oid", name: "oid"},
  { id: "name", name: "Name"},
  { name: "Update", formatter: (cell, row) => html(`<button data-id="${row.cells[0].data}">Update</button>`) }
  { name: "View Booking Details", formatter: (cell, row) => html(``) } // --> get booking_id from data without displaying booking_id as column in table
],
...
data: [
  {
    oid: "xxxx-1234",
    booking_id: "abcd-6789"
    name: "tom cruise"
  }
]
...
```

by having a way to access data from formatter, it opens up wider customization possibility to edit the row data for example: using modal or other ui component.

or the other way around, adding option to hide the specific column will help also.

example approach: http://fooplugins.github.io/FooTable/docs/examples/basic/row-toggle.html

**Comment by afshinm** [comment]
Sorry for the delay @cedriking -- I will proprieties this ticket.

**Comment by afshinm** [comment]
Added in 1.17.0: https://gridjs.io/docs/examples/cell-attributes
