### ISSUE TITLE
Access whole data list when pagination and server are enabled

### ISSUE THREAD

**Issue by imjulioc** [grid-js/gridjs#423]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

When configuring `{server: {enabled: true}, pagination: {enabled: true}}` then `this.config.pipeline.process()` only returns a thenable with the current pipeline (more like data displayed on the current table page).

If possible, it would be nice to be able to get the whole data list. That way writting plugins like *Copy all* would be more easy.

I'd imagine a property for accessing all cached data in a more simple way, because this is the "trick" I figured out:
`const _pipeline = this.config.pipeline;`

 `const { data } = _pipeline.steps.map(processor => _pipeline.cache.get(processor.id)).filter(element => Object.keys(element).includes('data'))[0]`

But I don't know if that is an efficient way.

**Comment by afshinm** [comment]
@imjulioc I'm not quite sure what "whole dataset" means when you have enabled the server-side features. Grid.js always pulls the rows that are required to render the current viewport (i.e if you are on page 1 with 10 records, only the first 10 records will be fetched from your server-side backend). 

Because of this lazy-loading behavior, Grid.js doesn't know anything about your entire dataset which is stored in your backend.

**Comment by afshinm** [comment]
But you can always skip the pipeline and interact with your underlying store directly, e.g. `gridjs_instance.config.storage...`: https://github.com/grid-js/gridjs/blob/master/packages/gridjs/src/storage/server.ts

**Comment by imjulioc** [comment]
Hi @afshinm, First off, thank you for the time you took to answer.
I made a mistake, mentioning the server option, I really just wanted to know how to avoid the pipeline. Glad to see you still understood what I was trying to ask. Again, sorry for the mistake and thanks!.> server
