### ISSUE TITLE
 I want to respond to the responsive web.

### ISSUE THREAD

**Issue by kimkanghyune** [grid-js/gridjs#920]
I wish there was a special function or option to respond to the responsive web.
If the width is reduced too much, the table will look weird.
I wonder if I should respond with css, or if that feature already exists, or if it will be added in the future.

**Comment by MehdiBenbahri** [comment]
Hi Kim,

By definition a table can't be responsive... That's the case for grid.js, datatable, or any kind of other table...
But there are some works-arounds 👍 

- You can disable auto width (it calculate automatically column width) and fix the column width.
- You can Hide column. (see https://gridjs.io/docs/examples/hidden-columns/)
- I don't know if you can do it with grid.js but in datatable you can "spread" a css class for all the column and hide it. I used Bootstrap 5 class (d-sm-none for example) to hide a column on mobile.

An other thing that grid.js doesn't support yet (i think) it's what people call "child row" or "detail row" : https://datatables.net/examples/api/row_details.html

I will make a specific demand for this one, because even on desktop it's very useful, for now i just make it by opening a modal.
